apiVersion: apps/v1

kind: Deployment
metadata:
  name: auctions-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: auctions
  template:
    metadata:
      labels:
        component: auctions
    spec:
      containers:
        - name: auctions
          image: tamshalev/auctions
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: '5000'
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-url
                  key: MONGODB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET